configuration: Gurobi HR
data_file: data/mznc2019/groupsplitter/u15g5pref0.dzn
error: "std::bad_alloc\nterminate called after throwing an instance of 'std::bad_alloc'\n\
  \  what():  std::bad_alloc"
model: data/mznc2019/groupsplitter/group.mzn
problem: groupsplitter
status: ERROR
